# File: utils/calculations.py

from sqlalchemy.orm import Session
from database.models import Bill, Point


def calculate_points(amount: float) -> float:
    """
    Calculate points based on bill amount.

    Args:
        amount (float): The bill amount.

    Returns:
        float: The calculated points.
    """
    return amount // 1000


def calculate_total_business(db: Session, wireman_id: int) -> float:
    """
    Calculate total business generated by a wireman.

    Args:
        db (Session): The database session.
        wireman_id (int): The ID of the wireman.

    Returns:
        float: The total business amount.
    """
    total_business = db.query(Bill.amount).filter(Bill.wireman_id == wireman_id).all()
    return sum(amount for (amount,) in total_business)


def calculate_total_points(db: Session, wireman_id: int) -> float:
    """
    Calculate total points earned by a wireman.

    Args:
        db (Session): The database session.
        wireman_id (int): The ID of the wireman.

    Returns:
        float: The total points earned.
    """
    point_record = db.query(Point).filter(Point.wireman_id == wireman_id).first()
    return point_record.total_points if point_record else 0